-- ============================================================
-- MIGRACION: Orden Medica - cabecera historica minima
-- Ejecutar sobre BD existente antes de desplegar hce-orden-medica actualizado.
-- ============================================================

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_DNI_PACIENTE VARCHAR2(12 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_TIPO_COBERTURA VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_TIPO_BENEFICIO VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_CONDICION VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PARENTESCO VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_ACTIVIDAD VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_SUB_ACTIVIDAD VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_SERVICIO VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD T_FECHA_ATENCION DATE;

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_IPRESS_CUI VARCHAR2(20 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PROF_NOMBRE VARCHAR2(255 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PROF_PROFESION VARCHAR2(100 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PROF_DOCUMENTO VARCHAR2(12 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PROF_COLEGIATURA VARCHAR2(30 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD V_PROF_RNE VARCHAR2(30 BYTE);

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    DROP CONSTRAINT CK_ORD_MED_ESTADO;

ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA
    ADD CONSTRAINT CK_ORD_MED_ESTADO CHECK (
        V_ESTADO IN ('BORRADOR','EMITIDA','ATENDIDA','ANULADA','OBSERVADA')
    );

CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_MED_DNI
    ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (V_DNI_PACIENTE);

-- Si se aplico una version anterior con snapshots no deseados:
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_NRO_HC;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_APELLIDOS_PACIENTE;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_NOMBRES_PACIENTE;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN T_FECHA_NAC;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_SEXO;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_IPRESS;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_IPRESS_SEDE;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_IPRESS_REGION;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA DROP COLUMN V_IPRESS_CATEGORIA;

-- Cuando no existan datos previos, convertir la columna en obligatoria.
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA MODIFY V_DNI_PACIENTE VARCHAR2(12 BYTE) NOT NULL;
-- ALTER TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA MODIFY V_IPRESS_CUI VARCHAR2(20 BYTE) NOT NULL;

COMMIT;
