/*
  Eliminacion directa de objetos del esquema SCH_HCE_ORDEN.
  Ejecutar con un usuario con permisos sobre el esquema.
*/

DROP TABLE SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA CASCADE CONSTRAINTS PURGE;
DROP TABLE SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS CASCADE CONSTRAINTS PURGE;
DROP TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET CASCADE CONSTRAINTS PURGE;
DROP TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_QUIMIOTERAPIA;
DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_HEMODIALISIS;
DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA_DET;
DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA;
