/*
  Esquema Orden Médica - SCH_HCE_ORDEN
  OAP: codigo recibido desde la atencion clinica origen.
*/

-- Secuencias
CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA_DET START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_HEMODIALISIS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_QUIMIOTERAPIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 1. Cabecera
CREATE TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID                    NUMBER(19,0),
    V_NRO_OAP               VARCHAR2(30 BYTE) NOT NULL,

    V_TIPO_ATENCION         VARCHAR2(2 BYTE) NOT NULL,
    I_ATENCION_ID           NUMBER(19,0) NOT NULL,
    I_ADMISION_ID           NUMBER(19,0),
    I_HISTORIA_CLINICA_ID   NUMBER(19,0) NOT NULL,
    V_DNI_PACIENTE          VARCHAR2(12 BYTE) NOT NULL,

    V_TIPO_ORDEN            VARCHAR2(30 BYTE) NOT NULL,

    I_EDAD                  NUMBER(3,0),
    V_TIPO_SEGURO           VARCHAR2(100 BYTE),
    V_TIPO_BENEFICIARIO     VARCHAR2(100 BYTE),
    V_PLAN_SEGURO           VARCHAR2(100 BYTE),
    V_TIPO_COBERTURA        VARCHAR2(100 BYTE),
    V_TIPO_BENEFICIO        VARCHAR2(100 BYTE),
    V_CONDICION             VARCHAR2(100 BYTE),
    V_PARENTESCO            VARCHAR2(100 BYTE),

    V_ACTIVIDAD             VARCHAR2(100 BYTE),
    V_SUB_ACTIVIDAD         VARCHAR2(100 BYTE),
    V_SERVICIO              VARCHAR2(100 BYTE),
    T_FECHA_ATENCION        DATE,

    V_IPRESS_CUI            VARCHAR2(20 BYTE) NOT NULL,

    V_PROF_NOMBRE           VARCHAR2(255 BYTE),
    V_PROF_PROFESION        VARCHAR2(100 BYTE),
    V_PROF_DOCUMENTO        VARCHAR2(12 BYTE),
    V_PROF_COLEGIATURA      VARCHAR2(30 BYTE),
    V_PROF_RNE              VARCHAR2(30 BYTE),

    V_NRO_APS               VARCHAR2(30 BYTE),
    V_NRO_CARTA_GARANTIA    VARCHAR2(30 BYTE),

    V_ESTADO                VARCHAR2(20 BYTE) DEFAULT 'EMITIDA' NOT NULL,

    T_FECHA_EMISION         DATE DEFAULT SYSDATE NOT NULL,
    T_CREATED_AT            DATE DEFAULT SYSDATE NOT NULL,
    V_CREATED_BY            VARCHAR2(50 BYTE) NOT NULL,
    T_UPDATED_AT            DATE,
    V_UPDATED_BY            VARCHAR2(50 BYTE),

    CONSTRAINT PK_TBL_ORD_MED PRIMARY KEY (I_ID),
    CONSTRAINT CK_ORD_MED_ESTADO CHECK (
        V_ESTADO IN ('BORRADOR','EMITIDA','ATENDIDA','ANULADA','OBSERVADA')
    ),
    CONSTRAINT CK_ORD_MED_TIPO_ATE CHECK (
        V_TIPO_ATENCION IN ('CE','CS','EM','HO')
    ),
    CONSTRAINT CK_ORD_MED_TIPO_ORD CHECK (
        V_TIPO_ORDEN IN ('LAB','IMG','PDI','PTE','TES','OTR','HEM','QUI')
    )
);

COMMENT ON TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA IS 'Cabecera de la orden medica generada desde una atencion clinica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.I_ID IS 'Identificador interno de la orden medica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_NRO_OAP IS 'Numero OAP recibido desde la atencion clinica origen. La orden medica se identifica tecnicamente por I_ID.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_TIPO_ATENCION IS 'Tipo de atencion origen. CE = Consulta Externa | CS = Consulta de Seguimiento | EM = Emergencia | HO = Hospitalizacion.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.I_ATENCION_ID IS 'Identificador de la atencion origen dentro del dominio indicado por V_TIPO_ATENCION.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.I_ADMISION_ID IS 'Identificador de admision asociado al origen de la orden, cuando aplica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.I_HISTORIA_CLINICA_ID IS 'Referencia a la historia clinica del paciente; no reemplaza la atencion origen.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_DNI_PACIENTE IS 'DNI del paciente denormalizado para busqueda directa de ordenes medicas.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_IPRESS_CUI IS 'Codigo CUI de la IPRESS asociado al momento de generar la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_PROF_DOCUMENTO IS 'Documento de identidad del profesional firmante o solicitante.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_TIPO_ORDEN IS 'Tipo exclusivo de orden. LAB = Laboratorio | IMG = Imagen | PDI = Procedimiento diagnostico | PTE = Procedimiento terapeutico programado | TES = Terapia especializada | OTR = Otros | HEM = Hemodialisis | QUI = Quimioterapia.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.I_EDAD IS 'Edad del paciente al generar la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_TIPO_SEGURO IS 'Snapshot del tipo de seguro asociado a la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_TIPO_BENEFICIARIO IS 'Snapshot del tipo de beneficiario asociado a la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_PLAN_SEGURO IS 'Snapshot del plan de seguro asociado a la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_NRO_APS IS 'Numero APS asociado a la orden, si aplica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_NRO_CARTA_GARANTIA IS 'Numero de carta de garantia asociado a la orden, si aplica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_ESTADO IS 'Estado de la orden medica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.T_FECHA_EMISION IS 'Fecha y hora de generacion de la orden medica.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.T_CREATED_AT IS 'Fecha de creacion auditada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_CREATED_BY IS 'Usuario que creo el registro.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.T_UPDATED_AT IS 'Fecha de ultima actualizacion auditada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA.V_UPDATED_BY IS 'Usuario que actualizo el registro.';

-- 2. Detalle de prestaciones
CREATE TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID                    NUMBER(19,0),
    I_ORDEN_MEDICA_ID       NUMBER(19,0) NOT NULL,

    V_TIPO                  VARCHAR2(3 BYTE) NOT NULL,
    V_CODIGO_CIE10          VARCHAR2(10 BYTE),
    V_CODIGO_CPMS           VARCHAR2(30 BYTE),
    V_CODIGO_SEGUS          VARCHAR2(30 BYTE),
    V_DESCRIPCION           VARCHAR2(500 BYTE) NOT NULL,

    N_CANTIDAD              NUMBER(10,2) DEFAULT 1,
    V_PRIORIDAD             VARCHAR2(20 BYTE) DEFAULT 'Normal',
    V_OBSERVACIONES         VARCHAR2(1000 BYTE),

    V_ESTADO                VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE',

    CONSTRAINT PK_TBL_ORD_DET PRIMARY KEY (I_ID),
    CONSTRAINT FK_ORDDET_ORDMED FOREIGN KEY (I_ORDEN_MEDICA_ID)
        REFERENCES SCH_HCE_ORDEN.TBL_ORDEN_MEDICA(I_ID),
    CONSTRAINT CK_ORDDET_TIPO CHECK (
        V_TIPO IN ('LAB','IMG','PDI','PTE','TES','OTR')
    )
);

COMMENT ON TABLE SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET IS 'Detalle general de prestaciones de una orden medica no especial.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.I_ID IS 'Identificador interno del detalle general.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.I_ORDEN_MEDICA_ID IS 'Orden medica propietaria del detalle.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_TIPO IS 'Tipo del detalle general. Todos los detalles de una orden deben corresponder a su tipo de orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_CODIGO_CIE10 IS 'Codigo CIE10 asociado a la prestacion.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_CODIGO_CPMS IS 'Codigo CPMS asociado a la prestacion.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_CODIGO_SEGUS IS 'Codigo SEGUS asociado a la prestacion.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_DESCRIPCION IS 'Descripcion de la prestacion solicitada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.N_CANTIDAD IS 'Cantidad solicitada para la prestacion.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_PRIORIDAD IS 'Prioridad de la prestacion solicitada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_OBSERVACIONES IS 'Observaciones clinicas del detalle.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET.V_ESTADO IS 'Estado del detalle general.';

-- 3. Hemodiálisis (0..1 por orden)
CREATE TABLE SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS (
    I_ID                    NUMBER(19,0),
    I_ORDEN_MEDICA_ID       NUMBER(19,0) NOT NULL,

    V_TIPO_DIALISIS         VARCHAR2(100 BYTE),
    V_FRECUENCIA            VARCHAR2(100 BYTE),
    I_DURACION_SESION_MIN   NUMBER(5,0),
    I_NUMERO_SESIONES       NUMBER(5,0),
    V_ACCESO_VASCULAR       VARCHAR2(200 BYTE),
    V_ANTICOAGULACION       VARCHAR2(200 BYTE),
    V_OBSERVACIONES         VARCHAR2(2000 BYTE),

    CONSTRAINT PK_TBL_ORD_HEMO PRIMARY KEY (I_ID),
    CONSTRAINT FK_ORDHEMO_ORDMED FOREIGN KEY (I_ORDEN_MEDICA_ID)
        REFERENCES SCH_HCE_ORDEN.TBL_ORDEN_MEDICA(I_ID),
    CONSTRAINT UQ_ORDHEMO_ORDMED UNIQUE (I_ORDEN_MEDICA_ID)
);

COMMENT ON TABLE SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS IS 'Detalle exclusivo de una orden medica de hemodialisis.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.I_ID IS 'Identificador interno del detalle de hemodialisis.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.I_ORDEN_MEDICA_ID IS 'Orden medica exclusiva de hemodialisis.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.V_TIPO_DIALISIS IS 'Tipo de dialisis indicada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.V_FRECUENCIA IS 'Frecuencia indicada para las sesiones.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.I_DURACION_SESION_MIN IS 'Duracion de cada sesion en minutos.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.I_NUMERO_SESIONES IS 'Numero de sesiones indicadas.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.V_ACCESO_VASCULAR IS 'Acceso vascular indicado.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.V_ANTICOAGULACION IS 'Anticoagulacion indicada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS.V_OBSERVACIONES IS 'Observaciones para la orden de hemodialisis.';

-- 4. Quimioterapia (0..1 por orden) — V_OBSERVACIONES duplicado corregido
CREATE TABLE SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA (
    I_ID                       NUMBER(19,0),
    I_ORDEN_MEDICA_ID          NUMBER(19,0) NOT NULL,

    V_DIAGNOSTICO_ONCOLOGICO   VARCHAR2(500 BYTE),
    V_ESTADIO                  VARCHAR2(100 BYTE),
    V_MEDICAMENTOS             VARCHAR2(500 BYTE),
    V_DOSIS                    VARCHAR2(500 BYTE),
    V_VIA                      VARCHAR2(100 BYTE),
    V_FRECUENCIA               VARCHAR2(100 BYTE),
    V_PROTOCOLO_TERAPEUTICO    VARCHAR2(300 BYTE),
    V_CICLO                    VARCHAR2(100 BYTE),
    I_DURACION_CICLO_DIAS      NUMBER(5,0),
    V_OBSERVACIONES            VARCHAR2(2000 BYTE),

    CONSTRAINT PK_TBL_ORD_QUIMIO PRIMARY KEY (I_ID),
    CONSTRAINT FK_ORDQUIMIO_ORDMED FOREIGN KEY (I_ORDEN_MEDICA_ID)
        REFERENCES SCH_HCE_ORDEN.TBL_ORDEN_MEDICA(I_ID),
    CONSTRAINT UQ_ORDQUIMIO_ORDMED UNIQUE (I_ORDEN_MEDICA_ID)
);

COMMENT ON TABLE SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA IS 'Detalle exclusivo de una orden medica de quimioterapia.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.I_ID IS 'Identificador interno del detalle de quimioterapia.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.I_ORDEN_MEDICA_ID IS 'Orden medica exclusiva de quimioterapia.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_DIAGNOSTICO_ONCOLOGICO IS 'Diagnostico oncologico asociado a la orden.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_ESTADIO IS 'Estadio oncologico indicado.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_MEDICAMENTOS IS 'Medicamentos indicados en el esquema.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_DOSIS IS 'Dosis indicada en el esquema.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_VIA IS 'Via de administracion indicada.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_FRECUENCIA IS 'Frecuencia del esquema de quimioterapia.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_PROTOCOLO_TERAPEUTICO IS 'Protocolo terapeutico asociado.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_CICLO IS 'Ciclo de quimioterapia indicado.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.I_DURACION_CICLO_DIAS IS 'Duracion del ciclo en dias.';
COMMENT ON COLUMN SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA.V_OBSERVACIONES IS 'Observaciones para la orden de quimioterapia.';

CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_MED_HC ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (I_HISTORIA_CLINICA_ID);
CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_MED_ADM ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (I_ADMISION_ID);
CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_MED_DNI ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (V_DNI_PACIENTE);
CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_MED_ATE ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (V_TIPO_ATENCION, I_ATENCION_ID);
CREATE INDEX SCH_HCE_ORDEN.IDX_ORD_DET_ORD ON SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (I_ORDEN_MEDICA_ID);
