/*
  Datos de ejemplo - Orden Medica
  Ejecutar DESPUES de SCH_HCE_ORDEN.ddl.sql.
*/

DELETE FROM SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA WHERE I_ORDEN_MEDICA_ID IN (1, 2, 3, 4, 5, 6, 7, 8);
DELETE FROM SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS WHERE I_ORDEN_MEDICA_ID IN (1, 2, 3, 4, 5, 6, 7, 8);
DELETE FROM SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET WHERE I_ORDEN_MEDICA_ID IN (1, 2, 3, 4, 5, 6, 7, 8);
DELETE FROM SCH_HCE_ORDEN.TBL_ORDEN_MEDICA WHERE I_ID IN (1, 2, 3, 4, 5, 6, 7, 8);

-- Cabeceras con todos los campos persistidos por Orden Medica.
INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    1, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'LAB', 42,
    'SaludPol', 'PNP en Actividad', 'Especifico', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Nefrologia', SYSDATE - 8,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-03142', 'EMITIDA', SYSDATE - 8, SYSDATE - 8, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    2, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'IMG', 42,
    'SaludPol', 'PNP en Actividad', 'Regular', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Medicina Interna', SYSDATE - 7,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-02801', 'EMITIDA', SYSDATE - 7, SYSDATE - 7, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    3, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'PDI', 42,
    'SaludPol', 'PNP en Actividad', 'Regular', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Gastroenterologia', SYSDATE - 6,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-02802', 'EMITIDA', SYSDATE - 6, SYSDATE - 6, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    4, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'PTE', 42,
    'SaludPol', 'PNP en Actividad', 'Regular', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Traumatologia', SYSDATE - 5,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-02803', 'EMITIDA', SYSDATE - 5, SYSDATE - 5, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    5, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'TES', 42,
    'SaludPol', 'PNP en Actividad', 'Regular', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Medicina Fisica', SYSDATE - 4,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-02804', 'EMITIDA', SYSDATE - 4, SYSDATE - 4, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    6, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'OTR', 42,
    'SaludPol', 'PNP en Actividad', 'Regular', 'Regular', 'Atencion Ambulatoria',
    'Titular', 'Titular', 'Atencion medica ambulatoria', 'Consulta medica', 'Nutricion', SYSDATE - 3,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-02805', 'EMITIDA', SYSDATE - 3, SYSDATE - 3, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    7, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'HEM', 42,
    'SaludPol', 'PNP en Actividad', 'Especifico', 'Especial', 'Hemodialisis',
    'Titular', 'Titular', 'Terapia renal sustitutiva', 'Hemodialisis cronica', 'Nefrologia', SYSDATE - 2,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-03143', 'EMITIDA', SYSDATE - 2, SYSDATE - 2, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA (
    I_ID, V_NRO_OAP, V_TIPO_ATENCION, I_ATENCION_ID, I_ADMISION_ID, I_HISTORIA_CLINICA_ID,
    V_DNI_PACIENTE, V_TIPO_ORDEN, I_EDAD,
    V_TIPO_SEGURO, V_TIPO_BENEFICIARIO, V_PLAN_SEGURO, V_TIPO_COBERTURA, V_TIPO_BENEFICIO,
    V_CONDICION, V_PARENTESCO, V_ACTIVIDAD, V_SUB_ACTIVIDAD, V_SERVICIO, T_FECHA_ATENCION,
    V_IPRESS_CUI, V_PROF_NOMBRE, V_PROF_PROFESION, V_PROF_DOCUMENTO, V_PROF_COLEGIATURA, V_PROF_RNE,
    V_NRO_APS, V_NRO_CARTA_GARANTIA, V_ESTADO, T_FECHA_EMISION, T_CREATED_AT, V_CREATED_BY
) VALUES (
    8, 'OAP-CE-00001', 'CE', 1, 1, 1, '05611249', 'QUI', 42,
    'SaludPol', 'PNP en Actividad', 'Especifico', 'Especial', 'Quimioterapia',
    'Titular', 'Titular', 'Tratamiento oncologico', 'Quimioterapia ambulatoria', 'Oncologia', SYSDATE - 1,
    '00013591', 'LUIS CARRANZA', 'Medico', '87654321', '12345', 'RNE-001',
    'APS-582941', 'CG-2026-03144', 'EMITIDA', SYSDATE - 1, SYSDATE - 1, 'SEED_DEMO'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (1, 1, 'LAB', 'N18.5', '80015', '850101', 'Hemograma completo automatizado', 1, 'Programado', 'Muestra en ayunas si corresponde.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (2, 1, 'LAB', 'N18.5', '82565', '850202', 'Dosaje de creatinina en sangre', 1, 'Urgente', 'Control de funcion renal.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (3, 1, 'LAB', 'N18.5', '84520', '850203', 'Urea en sangre', 1, 'Normal', 'Control bioquimico complementario.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (4, 2, 'IMG', 'R10.4', '76770', '870201', 'Ecografia abdominal superior', 1, 'Normal', 'Evaluar dolor abdominal persistente.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (5, 2, 'IMG', 'R07.9', '71046', '870102', 'Radiografia de torax frontal y lateral', 1, 'Preferente', 'Descartar compromiso pleuropulmonar.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (6, 2, 'IMG', 'M54.5', '72100', '870301', 'Radiografia de columna lumbosacra', 1, 'Programado', 'Evaluar dolor lumbar cronico.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (7, 3, 'PDI', 'K29.7', '43239', '830101', 'Endoscopia digestiva alta diagnostica', 1, 'Programado', 'Programar con preparacion previa.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (8, 4, 'PTE', 'M17.0', '20610', '840301', 'Infiltracion intraarticular programada', 1, 'Programado', 'Realizar bajo indicacion de traumatologia.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (9, 5, 'TES', 'I69.3', '97110', '880101', 'Terapia fisica neurorehabilitadora', 10, 'Preferente', 'Paquete de sesiones segun evolucion funcional.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO, V_CODIGO_CIE10, V_CODIGO_CPMS, V_CODIGO_SEGUS,
    V_DESCRIPCION, N_CANTIDAD, V_PRIORIDAD, V_OBSERVACIONES, V_ESTADO
) VALUES (10, 6, 'OTR', 'Z71.9', NULL, NULL, 'Evaluacion por nutricion clinica', 1, 'Normal', 'Evaluacion nutricional integral.', 'PENDIENTE');

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS (
    I_ID, I_ORDEN_MEDICA_ID, V_TIPO_DIALISIS, V_FRECUENCIA, I_DURACION_SESION_MIN,
    I_NUMERO_SESIONES, V_ACCESO_VASCULAR, V_ANTICOAGULACION, V_OBSERVACIONES
) VALUES (
    1, 7, 'Hemodialisis convencional', '3 veces por semana', 240, 12,
    'Fistula arteriovenosa', 'Heparina segun protocolo',
    'Controlar presion arterial pre y post sesion.'
);

INSERT INTO SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA (
    I_ID, I_ORDEN_MEDICA_ID, V_DIAGNOSTICO_ONCOLOGICO, V_ESTADIO,
    V_MEDICAMENTOS, V_DOSIS, V_VIA, V_FRECUENCIA,
    V_PROTOCOLO_TERAPEUTICO, V_CICLO, I_DURACION_CICLO_DIAS, V_OBSERVACIONES
) VALUES (
    1, 8, 'Neoplasia maligna de mama', 'IIA',
    'Doxorrubicina + ciclofosfamida', 'Segun superficie corporal', 'Intravenosa', 'Cada 21 dias',
    'AC', 'Ciclo 1', 21, 'Verificar hemograma y funcion renal antes de infusion.'
);

COMMIT;

DECLARE
    v_max_orden   NUMBER;
    v_max_det     NUMBER;
    v_max_hemo    NUMBER;
    v_max_quimio  NUMBER;
BEGIN
    SELECT NVL(MAX(I_ID), 0) + 1 INTO v_max_orden FROM SCH_HCE_ORDEN.TBL_ORDEN_MEDICA;
    SELECT NVL(MAX(I_ID), 0) + 1 INTO v_max_det FROM SCH_HCE_ORDEN.TBL_ORDEN_MEDICA_DET;
    SELECT NVL(MAX(I_ID), 0) + 1 INTO v_max_hemo FROM SCH_HCE_ORDEN.TBL_ORDEN_HEMODIALISIS;
    SELECT NVL(MAX(I_ID), 0) + 1 INTO v_max_quimio FROM SCH_HCE_ORDEN.TBL_ORDEN_QUIMIOTERAPIA;

    EXECUTE IMMEDIATE 'DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA START WITH ' || v_max_orden || ' INCREMENT BY 1 NOCACHE NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA_DET';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_MEDICA_DET START WITH ' || v_max_det || ' INCREMENT BY 1 NOCACHE NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_HEMODIALISIS';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_HEMODIALISIS START WITH ' || v_max_hemo || ' INCREMENT BY 1 NOCACHE NOCYCLE';
    EXECUTE IMMEDIATE 'DROP SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_QUIMIOTERAPIA';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SCH_HCE_ORDEN.SEQ_ORDEN_QUIMIOTERAPIA START WITH ' || v_max_quimio || ' INCREMENT BY 1 NOCACHE NOCYCLE';
END;
/
