-- Sequences

CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ATENCION"            INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ANT_PERSONAL"        INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_EXAMEN_FISICO"       INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ANT_ALERGICO"        INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ANT_FAMILIAR"        INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ANT_GINECO"          INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_ANT_QUIRURGICO"      INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_APP"                 INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_DECISION_CLINICA"    INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_DECISION_CONTROL"    INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_DIAGNOSTICO"         INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_EXAMEN_REGION"       INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_HABITO_RIESGO"       INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_INDICACION_NO_FARM"  INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_TRATAMIENTO"         INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_LISTA_PROBLEMA"      INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_MED_PLAN_CONTROL"    INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_MEDICACION"          INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_MOTIVO_CONSULTA"     INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_PLAN_CONTROL"        INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_REVISION_SISTEMA"    INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_SOAP_ANALISIS"       INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_SOAP_OBJETIVO"       INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_SOAP_PLAN"           INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_SOAP_SUBJETIVO"      INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE "SCH_HCE_CONSULTA"."SEQ_SOLICITUD_APOYO"     INCREMENT BY 1 START WITH 1 NOCACHE;


-- TBL_ATENCION (la base de todo)

CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ATENCION" (
  "I_ID"                  NUMBER(19,0)       NOT NULL,
  "I_ADMISION_ID"         NUMBER(19,0)       NOT NULL,
  "V_TIPO_ATENCION"       VARCHAR2(2 BYTE)   NOT NULL,
  "T_FECHA_ATENCION"      DATE               NOT NULL,
  "V_SERVICIO"            VARCHAR2(100 BYTE),
  "V_DNI_PACIENTE"        VARCHAR2(12 BYTE),
  "I_CE_ATENCION_ID"      NUMBER(19,0),
  "V_IPRESS_CUI"          VARCHAR2(20 BYTE),
  "V_ESTADO"              VARCHAR2(20 BYTE)  DEFAULT 'ABIERTA'  NOT NULL,
  "T_CREATED_AT"          DATE               DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)  NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_ATENCION" PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_ATE_ESTADO"   CHECK ("V_ESTADO" IN ('ABIERTA','COMPLETADA','ANULADA'))
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_ATENCION" IS 'Registro maestro de cada atención médica. Padre de CE, Control, etc.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_ATENCION"."V_TIPO_ATENCION"       IS 'CS = Consulta Control | CE = Consulta Externa.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_ATENCION"."V_SERVICIO"            IS 'Especialidad/servicio de la atención. Requerido para CE.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_ATENCION"."V_DNI_PACIENTE"        IS 'DNI del paciente denormalizado para consultas de historial sin pasar por filiacion.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_ATENCION"."I_CE_ATENCION_ID"      IS 'FK a la CE padre (solo filas CS). Null para atenciones CE.';


-- TBL_ANT_PERSONAL

CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" (
  "I_ID"                  NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)        NOT NULL,
  "V_TIPO_PARTO"          VARCHAR2(10 BYTE),
  "I_EDAD_GESTACIONAL"    NUMBER(3,0),
  "N_PESO_NACER"          NUMBER(5,2),
  "N_TALLA_NACER"         NUMBER(5,1),
  "V_APGAR"               VARCHAR2(20 BYTE),
  "V_COMP_NEONATAL"       VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_COMP_NEONATAL_DESC"  VARCHAR2(500 BYTE),
  "T_CREATED_AT"          DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_ANT_PERS"    PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_ANTP_ATENCION"   UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_ANTP_COMP_NEO"   CHECK       ("V_COMP_NEONATAL" IN ('S','N')),
  CONSTRAINT "FK_ANTP_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
  -- CONSTRAINT "CK_ANTP_PARTO"  CHECK (V_TIPO_PARTO IN ('Vaginal','Cesárea') OR V_TIPO_PARTO IS NULL)
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" IS 'Tab 2 Consulta Externa: Cabecera antecedentes personales + datos perinatales.';


-- TBL_EXAMEN_FISICO

CREATE TABLE "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO" (
  "I_ID"              NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"     NUMBER(19,0)        NOT NULL,
  "I_PA_SISTOLICA"    NUMBER(3,0),
  "I_PA_DIASTOLICA"   NUMBER(3,0),
  "I_FC"              NUMBER(5,0),
  "I_FR"              NUMBER(5,0),
  "N_TEMPERATURA"     NUMBER(4,1),
  "N_SAT_O2"          NUMBER(5,2),
  "N_PESO"            NUMBER(6,2),
  "N_TALLA"           NUMBER(5,1),
  "N_IMC"             NUMBER(5,2),
  "T_CREATED_AT"      DATE               DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"      VARCHAR2(50 BYTE)  NOT NULL,
  "T_UPDATED_AT"      DATE,
  "V_UPDATED_BY"      VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_EX_FIS"           PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_EXFIS_ATENCION"       UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_EXFIS_PA_SISTOLICA"   CHECK ("I_PA_SISTOLICA"  >= 1),
  CONSTRAINT "CK_EXFIS_PA_DIASTOLICA"  CHECK ("I_PA_DIASTOLICA" >= 1),
  CONSTRAINT "FK_EXFISICO_ATENCION"    FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO" IS 'Tab 5 CE: Signos vitales y antropometría del examen físico.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO"."I_PA_SISTOLICA"  IS 'Presión arterial sistólica (max) en mmHg.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO"."I_PA_DIASTOLICA" IS 'Presión arterial diastólica (min) en mmHg.';


-- Hijos de TBL_ANT_PERSONAL

-- TBL_ANT_ALERGICO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ANT_ALERGICO" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"   NUMBER(19,0)        NOT NULL,
  "V_ALERGIA_MED"       VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_ALERGIA_MED_DESC"  VARCHAR2(300 BYTE),
  "V_ALERGIA_ALI"       VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_ALERGIA_ALI_DESC"  VARCHAR2(300 BYTE),
  "V_ALERGIA_OTROS"     VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_ALERGIA_OTROS_DESC" VARCHAR2(300 BYTE),
  "V_TIPO_REACCION"     VARCHAR2(30 BYTE),

  CONSTRAINT "PK_TBL_ALERG"   PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_ALERG_ANTP"  UNIQUE      ("I_ANT_PERSONAL_ID"),
  CONSTRAINT "CK_ALERG_MED"   CHECK ("V_ALERGIA_MED"   IN ('S','N')),
  CONSTRAINT "CK_ALERG_ALI"   CHECK ("V_ALERGIA_ALI"   IN ('S','N')),
  CONSTRAINT "CK_ALERG_OTR"   CHECK ("V_ALERGIA_OTROS" IN ('S','N')),
  CONSTRAINT "CK_ALERG_TIPO"  CHECK ("V_TIPO_REACCION"  IN ('Leve','Moderada','Severa / Anafilaxia') OR "V_TIPO_REACCION" IS NULL),
  CONSTRAINT "FK_ALERG_ANTP"  FOREIGN KEY ("I_ANT_PERSONAL_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_ANT_ALERGICO" IS 'Tab 2 CE: Antecedentes alérgicos (1:1 con ant_personal).';

-- TBL_ANT_GINECO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ANT_GINECO" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"   NUMBER(19,0)        NOT NULL,
  "I_MENARQUIA"         NUMBER(3,0),
  "I_GESTACIONES"       NUMBER(3,0),
  "I_PARTOS"            NUMBER(3,0),
  "I_CESAREAS"          NUMBER(3,0),
  "I_ABORTOS"           NUMBER(3,0),
  "T_FUR"               DATE,
  "V_MENOPAUSIA"        VARCHAR2(1 BYTE)    DEFAULT 'N',
  "I_MENOPAUSIA_ANO"    NUMBER(4,0),
  "V_COMP_OBSTETRICAS"  VARCHAR2(1000 BYTE),

  CONSTRAINT "PK_TBL_GINECO"   PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_GINECO_ANTP"  UNIQUE      ("I_ANT_PERSONAL_ID"),
  CONSTRAINT "CK_GINECO_MENO"  CHECK       ("V_MENOPAUSIA" IN ('S','N')),
  CONSTRAINT "FK_GINECO_ANTP"  FOREIGN KEY ("I_ANT_PERSONAL_ID")
      REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_ANT_GINECO" IS 'Tab 2 CE: Antecedentes gineco-obstétricos. Solo para pacientes de sexo femenino.';

-- TBL_ANT_QUIRURGICO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ANT_QUIRURGICO" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"   NUMBER(19,0)        NOT NULL,
  "V_PROCEDIMIENTO"     VARCHAR2(4000 BYTE)  NOT NULL,
  "I_ANO"               NUMBER(4,0),
  "V_COMPLICACIONES"    VARCHAR2(500 BYTE),

  CONSTRAINT "PK_TBL_ANT_QUIR" PRIMARY KEY ("I_ID"),
  CONSTRAINT "FK_ANTQ_ANTP"   FOREIGN KEY ("I_ANT_PERSONAL_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_ANT_QUIRURGICO" IS 'Tab 2 CE: Antecedentes quirúrgicos del paciente.';

-- TBL_APP
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_APP" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"   NUMBER(19,0)        NOT NULL,
  "V_CONDICION"         VARCHAR2(100 BYTE)  NOT NULL,
  "V_TIENE"             VARCHAR2(1 BYTE)    DEFAULT 'N',
  "I_ANO_DX"            NUMBER(4,0),
  "V_TRATAMIENTO_ACTUAL" VARCHAR2(300 BYTE),
  "V_OBSERVACIONES"     VARCHAR2(500 BYTE),

  CONSTRAINT "PK_TBL_APP"  PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_APP_TIENE" CHECK ("V_TIENE" IN ('S','N')),
  CONSTRAINT "FK_APP_ANTP" FOREIGN KEY ("I_ANT_PERSONAL_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_APP" IS 'Tab 2 CE: Antecedentes Personales Patológicos. Una fila por condición.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_APP"."V_CONDICION" IS 'Hipertensión arterial | Diabetes Mellitus | Dislipidemia | Cardiopatía | ACV/TIA | Asma/EPOC | TBC | ERC | Enf. Tiroidea | Cáncer | Otra.';

-- TBL_HABITO_RIESGO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_HABITO_RIESGO" (
  "I_ID"                  NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"     NUMBER(19,0)        NOT NULL,
  "V_TABACO"              VARCHAR2(15 BYTE)   DEFAULT 'No',
  "N_TABACO_PAQUETES_ANO" NUMBER(5,1),
  "V_ALCOHOL"             VARCHAR2(15 BYTE)   DEFAULT 'No',
  "V_DROGAS"              VARCHAR2(5 BYTE)    DEFAULT 'No',
  "V_DROGAS_TIPO"         VARCHAR2(200 BYTE),
  "V_SEDENTARISMO"        VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_OTROS_FACTORES"      VARCHAR2(500 BYTE),

  CONSTRAINT "PK_TBL_HABITO"     PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_HABITO_ANTP"    UNIQUE      ("I_ANT_PERSONAL_ID"),
  CONSTRAINT "CK_HABITO_TABACO"  CHECK ("V_TABACO"       IN ('No','Exfumador','Activo')    OR "V_TABACO" IS NULL),
  CONSTRAINT "CK_HABITO_ALC"     CHECK ("V_ALCOHOL"      IN ('No','Social','Frecuente')    OR "V_ALCOHOL" IS NULL),
  CONSTRAINT "CK_HABITO_SEDN"    CHECK ("V_SEDENTARISMO" IN ('S','N')),
  CONSTRAINT "FK_HABRIESGO_ATENCION" FOREIGN KEY ("I_ANT_PERSONAL_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_HABITO_RIESGO" IS 'Tab 2 CE: Hábitos nocivos y factores de riesgo (1:1 con ant_personal).';

-- TBL_MEDICACION_CRONICA
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_MEDICACION_CRONICA" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ANT_PERSONAL_ID"   NUMBER(19,0)        NOT NULL,
  "V_FARMACO"           VARCHAR2(200 BYTE)  NOT NULL,
  "V_DOSIS"             VARCHAR2(50 BYTE),
  "V_FRECUENCIA"        VARCHAR2(50 BYTE),
  "V_INDICACION"        VARCHAR2(300 BYTE),

  CONSTRAINT "PK_TBL_MED_CRON"  PRIMARY KEY ("I_ID"),
  CONSTRAINT "FK_MEDCRON_ANTP"  FOREIGN KEY ("I_ANT_PERSONAL_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_MEDICACION_CRONICA" IS 'Tab 2 CE: Medicación crónica actual del paciente.';


-- TBL_ANT_FAMILIAR
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_ANT_FAMILIAR" (
  "I_ID"            NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"   NUMBER(19,0)        NOT NULL,
  "V_ENFERMEDAD"    VARCHAR2(100 BYTE)  NOT NULL,
  "V_PADRE"         VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_MADRE"         VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_HERMANOS"      VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_ABUELOS"       VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_OTROS"         VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_OBSERVACIONES" VARCHAR2(500 BYTE),

  CONSTRAINT "PK_TBL_ANT_FAM"    PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_ANTFAM_PADRE"   CHECK ("V_PADRE"    IN ('S','N')),
  CONSTRAINT "CK_ANTFAM_MADRE"   CHECK ("V_MADRE"    IN ('S','N')),
  CONSTRAINT "CK_ANTFAM_HERM"    CHECK ("V_HERMANOS" IN ('S','N')),
  CONSTRAINT "CK_ANTFAM_ABUEL"   CHECK ("V_ABUELOS"  IN ('S','N')),
  CONSTRAINT "CK_ANTFAM_OTROS"   CHECK ("V_OTROS"    IN ('S','N')),
  CONSTRAINT "FK_ANTFAM_ATENCION" FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_ANT_FAMILIAR" IS 'Tab 3 CE: Antecedentes familiares. Una fila por enfermedad.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_ANT_FAMILIAR"."V_ENFERMEDAD" IS 'HTA | Diabetes Mellitus | Cáncer | Cardiopatía | ACV | TBC | Enf. Mental | Enf. Renal.';

-- TBL_DECISION_CLINICA
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_DECISION_CLINICA" (
  "I_ID"                  NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)         NOT NULL,
  "V_DECISION_ALTA"       VARCHAR2(40 BYTE),
  "T_FECHA_PROXIMA_CITA"  DATE,
  "V_ESPECIALIDAD_REF"    VARCHAR2(100 BYTE),
  "V_PLAN_MANEJO"         VARCHAR2(2000 BYTE),
  "V_PRONOSTICO"          VARCHAR2(1000 BYTE),
  "V_OBSERVACIONES"       VARCHAR2(1000 BYTE),
  "V_MEDICO_NOMBRE"       VARCHAR2(255 BYTE),
  "V_MEDICO_CMP"          VARCHAR2(30 BYTE),
  "V_FIRMA_DIGITAL"       VARCHAR2(100 BYTE),
  "V_IPRESS_CUI"          VARCHAR2(20 BYTE),
  "T_CREATED_AT"          DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_DEC_CLIN"       PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_DECCLIN_ATENCION"   UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_DECCLIN_ALTA"       CHECK ("V_DECISION_ALTA" IN (
      'Alta con cita','Alta sin cita','Hospitalización',
      'Referencia','Contra-referencia','Emergencia'
  ) OR "V_DECISION_ALTA" IS NULL),
  CONSTRAINT "FK_DECCLINICA_ATENCION" FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_DECISION_CLINICA" IS 'Tab 10 CE: Decisión clínica, alta, plan de manejo y firma del médico.';

-- TBL_DECISION_CONTROL
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_DECISION_CONTROL" (
  "I_ID"                    NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"           NUMBER(19,0)         NOT NULL,
  "V_DECISION"              VARCHAR2(60 BYTE),
  "V_REF_PNP_IPRESS"        VARCHAR2(255 BYTE),
  "V_REF_PNP_MOTIVO"        VARCHAR2(500 BYTE),
  "V_REF_NOPNP_IPRESS"      VARCHAR2(255 BYTE),
  "V_REF_NOPNP_MOTIVO"      VARCHAR2(500 BYTE),
  "V_PROF_NOMBRES"          VARCHAR2(255 BYTE),
  "V_PROF_DOC_IDENT"        VARCHAR2(12 BYTE),
  "V_PROF_COLEGIATURA"      VARCHAR2(30 BYTE),
  "V_PROF_REG_ESPECIALIDAD" VARCHAR2(30 BYTE),
  "V_PROF_FIRMA_DIGITAL"    VARCHAR2(100 BYTE),
  "T_FECHA_CIERRE"          DATE,
  "V_IPRESS_CUI"            VARCHAR2(20 BYTE),
  "V_LOG_USUARIO"           VARCHAR2(50 BYTE),
  "V_LOG_IPRESS_ORIGEN"     VARCHAR2(255 BYTE),
  "V_LOG_ACCION"            VARCHAR2(100 BYTE)  DEFAULT 'REGISTRO_CONSULTA_CONTROL',
  "T_LOG_FECHA"             DATE                DEFAULT SYSDATE,
  "T_CREATED_AT"            DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"            VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"            DATE,
  "V_UPDATED_BY"            VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_DEC_CTRL"       PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_DECCTRL_ATENCION"   UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_DECCTRL_DEC"        CHECK ("V_DECISION" IN (
      'Alta','Continúa seguimiento de control ambulatorio','Referencia','Hospitalización'
  ) OR "V_DECISION" IS NULL),
  CONSTRAINT "FK_DECCTRL_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_DECISION_CONTROL" IS 'Tab 5 CC: Decisión clínica del control con datos del profesional y log de auditoría.';

-- TBL_DIAGNOSTICO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"       NUMBER(19,0)        NOT NULL,
  "I_CIE10_ID"          NUMBER(19,0),
  "V_CODIGO_CIE10"      VARCHAR2(10 BYTE),
  "V_DESCRIPCION"       VARCHAR2(500 BYTE)  NOT NULL,
  "V_TIPO"              VARCHAR2(20 BYTE)   DEFAULT 'Presuntivo',
  "V_CASO"              VARCHAR2(15 BYTE)   DEFAULT 'Nuevo',
  "I_NRO_PROBLEMA_ASOC" NUMBER(3,0),

  CONSTRAINT "PK_TBL_DIAG"              PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_DIAG_TIPO"             CHECK ("V_TIPO" IN ('Presuntivo','Definitivo','Descartado','Repetitivo') OR "V_TIPO" IS NULL),
  CONSTRAINT "CK_DIAG_CASO"             CHECK ("V_CASO" IN ('Nuevo','Repetido') OR "V_CASO" IS NULL),
  CONSTRAINT "FK_DIAGNOSTICO_ATENCION"  FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO" IS 'Tab 7 CE: Diagnósticos CIE-10 registrados en la atención.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO"."V_TIPO" IS 'Presuntivo | Definitivo | Descartado | Repetitivo.';

-- TBL_INDICACION_NO_FARM
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_INDICACION_NO_FARM" (
  "I_ID"            NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"   NUMBER(19,0)         NOT NULL,
  "V_INDICACIONES"  VARCHAR2(2000 BYTE),

  CONSTRAINT "PK_TBL_IND_NO_FARM"     PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_INDNOFARM_ATE"       UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "FK_INDNOFARM_ATENCION"  FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_INDICACION_NO_FARM" IS 'Tab 8 CE: Indicaciones no farmacológicas (dieta, reposo, actividad fsica, etc.).';

-- TBL_LISTA_PROBLEMA
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_LISTA_PROBLEMA" (
  "I_ID"                    NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"           NUMBER(19,0)        NOT NULL,
  "I_NRO_PROBLEMA"          NUMBER(3,0)         NOT NULL,
  "V_DESCRIPCION"           VARCHAR2(500 BYTE)  NOT NULL,
  "V_ESTADO"                VARCHAR2(25 BYTE)   DEFAULT 'Activo',
  "T_FECHA_IDENTIFICACION"  DATE,

  CONSTRAINT "PK_TBL_LISTA_PROB"      PRIMARY KEY ("I_ID"),
  CONSTRAINT "FK_LISTPROB_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
  -- CONSTRAINT "CK_LISTPROB_ESTADO" CHECK (V_ESTADO IN ('Activo','Resuelto','En seguimiento') OR V_ESTADO IS NULL)
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_LISTA_PROBLEMA" IS 'Tab 6 CE: Lista activa de problemas del paciente en esta atención.';

-- TBL_MED_PLAN_CONTROL
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_MED_PLAN_CONTROL" (
  "I_ID"            NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"   NUMBER(19,0)        NOT NULL,
  "V_CODIGO"        VARCHAR2(30 BYTE),
  "V_FARMACO"       VARCHAR2(200 BYTE)  NOT NULL,
  "V_DOSIS"         VARCHAR2(10 BYTE),
  "V_VIA"           VARCHAR2(10 BYTE),
  "V_FRECUENCIA"    VARCHAR2(3 BYTE),
  "V_DURACION"      VARCHAR2(8 BYTE),
  "V_CONDUCTA"      VARCHAR2(15 BYTE),

  CONSTRAINT "PK_TBL_MED_PLAN"       PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_MEDPLAN_CONDUCTA"   CHECK ("V_CONDUCTA" IN ('Mantener','Ajustar','Cambiar','Suspender') OR "V_CONDUCTA" IS NULL),
  CONSTRAINT "FK_MEDPLAN_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
  -- CONSTRAINT "CK_MEDPLAN_VIA"    CHECK (V_VIA IN ('Oral','EV','IM','Típico','Inhalado') OR V_VIA IS NULL)
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_MED_PLAN_CONTROL" IS 'Tab 4 CC: Medicación en el plan global de control con su conducta.';

-- TBL_MOTIVO_CONSULTA
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_MOTIVO_CONSULTA" (
  "I_ID"                  NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)         NOT NULL,
  "V_MOTIVO"              VARCHAR2(500 BYTE)   NOT NULL,
  "V_TIEMPO_ENFERMEDAD"   VARCHAR2(50 BYTE),
  "V_FORMA_INICIO"        VARCHAR2(20 BYTE),
  "V_CURSO"               VARCHAR2(20 BYTE),
  "V_ENFERMEDAD_ACTUAL"   VARCHAR2(2000 BYTE),
  "V_SINTOMAS_SIGNOS"     VARCHAR2(2000 BYTE),
  "V_RELATO_CRONOLOGICO"  VARCHAR2(2000 BYTE),
  "V_FACTORES_MOD"        VARCHAR2(1000 BYTE),
  "V_TRATAMIENTOS_PREVIOS" VARCHAR2(1000 BYTE),
  "V_OAP_EPISODIO"        VARCHAR2(30 BYTE),
  "T_CREATED_AT"          DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_MOTIVO"        PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_MOTIVO_ATENCION"   UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_MOTIVO_FORMA"      CHECK ("V_FORMA_INICIO" IN ('Insidioso','Brusco','Gradual')       OR "V_FORMA_INICIO" IS NULL),
  CONSTRAINT "CK_MOTIVO_CURSO"      CHECK ("V_CURSO"        IN ('Progresivo','Regresivo','Estacionario','Intermitente') OR "V_CURSO" IS NULL),
  CONSTRAINT "FK_MOTIVO_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_MOTIVO_CONSULTA" IS 'Tab 1 Consulta Externa: Motivo de consulta y enfermedad actual.';

-- TBL_PLAN_CONTROL
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_PLAN_CONTROL" (
  "I_ID"              NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"     NUMBER(19,0)         NOT NULL,
  "T_PROXIMA_CITA"    DATE,
  "V_INDICACIONES"    VARCHAR2(2000 BYTE),
  "V_CRITERIOS_ALARMA" VARCHAR2(2000 BYTE),

  CONSTRAINT "PK_TBL_PLAN_CTRL"       PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_PLANCTRL_ATENCION"   UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "FK_PLANCTRL_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_PLAN_CONTROL" IS 'Tab 4 CC: Plan global de control y seguimiento, cita, indicaciones y criterios de alarma.';

-- TBL_REVISION_SISTEMA
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_REVISION_SISTEMA" (
  "I_ID"            NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"   NUMBER(19,0)        NOT NULL,
  "V_SISTEMA"       VARCHAR2(50 BYTE)   NOT NULL,
  "V_SINTOMA"       VARCHAR2(100 BYTE)  NOT NULL,
  "V_PRESENTE"      VARCHAR2(1 BYTE)    DEFAULT 'N',
  "V_OBSERVACION"   VARCHAR2(300 BYTE),

  CONSTRAINT "PK_TBL_REV_SIST"       PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_REVSIST_PRESENTE"   CHECK ("V_PRESENTE" IN ('S','N')),
  CONSTRAINT "FK_REVSIST_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_REVISION_SISTEMA" IS 'Tab 4 CE: Revisión por sistemas. Una fila por síntoma revisado.';

-- TBL_SOAP_ANALISIS
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_ANALISIS" (
  "I_ID"                NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"       NUMBER(19,0)        NOT NULL,
  "V_EVOLUCION_ESTADO"  VARCHAR2(20 BYTE),
  "V_DIAG_ACTUALIZADO"  VARCHAR2(500 BYTE),
  "V_CAMBIOS_SEVERIDAD"  VARCHAR2(500 BYTE),
  "V_EVAL_TERAPEUTICA"  VARCHAR2(500 BYTE),
  "T_CREATED_AT"        DATE               DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"        VARCHAR2(50 BYTE)  NOT NULL,
  "T_UPDATED_AT"        DATE,
  "V_UPDATED_BY"        VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_SOAP_A"        PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_SOAPA_ATENCION"    UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "FK_SOAPA_ATENCION"    FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
  -- CONSTRAINT "CK_SOAPA_EVOL"        CHECK (V_EVOLUCION_ESTADO IN ('Mejoría','Igual','Peor','Resuelto') OR V_EVOLUCION_ESTADO IS NULL)
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_ANALISIS" IS 'Control/Seguimiento SOAP-A: Análisis y evaluación médica.';

-- TBL_SOAP_OBJETIVO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_OBJETIVO" (
  "I_ID"                  NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)         NOT NULL,
  "I_PA_SISTOLICA"        NUMBER(3,0),
  "I_PA_DIASTOLICA"       NUMBER(3,0),
  "I_FC"                  NUMBER(5,0),
  "I_FR"                  NUMBER(5,0),
  "N_TEMPERATURA"         NUMBER(4,1),
  "N_SAT_O2"              NUMBER(5,2),
  "N_PESO"                NUMBER(6,2),
  "N_TALLA"               NUMBER(5,1),
  "N_IMC"                 NUMBER(5,2),
  "V_HALLAZGOS_FISICOS"   VARCHAR2(2000 BYTE),
  "V_RESULT_ESTUDIOS"     VARCHAR2(2000 BYTE),
  "V_COMPARACION_PREVIA"  VARCHAR2(1000 BYTE),
  "T_CREATED_AT"          DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_SOAP_O"            PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_SOAFO_ATENCION"        UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_SOAFO_PA_SISTOLICA"    CHECK ("I_PA_SISTOLICA"  >= 1),
  CONSTRAINT "CK_SOAFO_PA_DIASTOLICA"   CHECK ("I_PA_DIASTOLICA" >= 1),
  CONSTRAINT "FK_SOAFO_ATENCION"        FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_SOAP_OBJETIVO" IS 'Control/Seguimiento SOAP-O: Datos objetivos (vitales, hallazgos, resultados).';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_SOAP_OBJETIVO"."I_PA_SISTOLICA"  IS 'Presion arterial sistolica (max) en mmHg.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_SOAP_OBJETIVO"."I_PA_DIASTOLICA" IS 'Presion arterial diastolica (min) en mmHg.';

-- TBL_SOAP_PLAN
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_PLAN" (
  "I_ID"              NUMBER(19,0)          NOT NULL,
  "I_ATENCION_ID"     NUMBER(19,0)          NOT NULL,
  "V_MANTENER_TRAT"   VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_AJUSTAR_DOSIS"   VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_CAMBIAR_ESQUEMA" VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_SUSPENDER_TRAT"  VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_NUEVOS_ESTUDIOS" VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_INTERCONSULTA"   VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_ALTA_PROBLEMA"   VARCHAR2(1 BYTE)      DEFAULT 'N',
  "V_DETALLES_PLAN"   VARCHAR2(2000 BYTE),
  "T_CREATED_AT"      DATE                  DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"      VARCHAR2(50 BYTE)     NOT NULL,
  "T_UPDATED_AT"      DATE,
  "V_UPDATED_BY"      VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_SOAP_P"        PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_SOAPP_ATENCION"    UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "CK_SOAPP_MANTENER"    CHECK ("V_MANTENER_TRAT"   IN ('S','N')),
  CONSTRAINT "CK_SOAPP_AJUSTAR"     CHECK ("V_AJUSTAR_DOSIS"   IN ('S','N')),
  CONSTRAINT "CK_SOAPP_CAMBIAR"     CHECK ("V_CAMBIAR_ESQUEMA" IN ('S','N')),
  CONSTRAINT "CK_SOAPP_SUSPENDER"   CHECK ("V_SUSPENDER_TRAT"  IN ('S','N')),
  CONSTRAINT "CK_SOAPP_ESTUDIOS"    CHECK ("V_NUEVOS_ESTUDIOS" IN ('S','N')),
  CONSTRAINT "CK_SOAPP_INTERCONS"   CHECK ("V_INTERCONSULTA"   IN ('S','N')),
  CONSTRAINT "CK_SOAPP_ALTA"        CHECK ("V_ALTA_PROBLEMA"   IN ('S','N')),
  CONSTRAINT "FK_SOAPP_ATENCION"    FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_PLAN" IS 'Control/Seguimiento SOAP-P: Plan terapeutico (conductas marcadas + detalle).';

-- TBL_SOAP_SUBJETIVO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_SUBJETIVO" (
  "I_ID"                NUMBER(19,0)          NOT NULL,
  "I_ATENCION_ID"       NUMBER(19,0)          NOT NULL,
  "V_EVOLUCION"         VARCHAR2(2000 BYTE),
  "V_PERSISTENCIA"      VARCHAR2(1000 BYTE),
  "V_ADHERENCIA"        VARCHAR2(1000 BYTE),
  "V_EVENTOS_ADVERSOS"  VARCHAR2(1000 BYTE),
  "T_CREATED_AT"        DATE                  DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"        VARCHAR2(50 BYTE)     NOT NULL,
  "T_UPDATED_AT"        DATE,
  "V_UPDATED_BY"        VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_SOAP_S"        PRIMARY KEY ("I_ID"),
  CONSTRAINT "UQ_SOAPS_ATENCION"    UNIQUE      ("I_ATENCION_ID"),
  CONSTRAINT "FK_SOAPS_ATENCION"    FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_SOAP_SUBJETIVO" IS 'Control/Seguimiento SOAP-S: Información subjetiva del paciente.';

-- TBL_SOLICITUD_APOYO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_SOLICITUD_APOYO" (
  "I_ID"                  NUMBER(19,0)        NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)        NOT NULL,
  "V_TIPO"                VARCHAR2(100 BYTE)  NOT NULL,
  "V_DESCRIPCION"         VARCHAR2(300 BYTE)  NOT NULL,
  "V_PRIORIDAD"           VARCHAR2(15 BYTE)   DEFAULT 'Normal',
  "V_OBSERVACIONES"       VARCHAR2(500 BYTE),
  "V_ID_SUBTIPO_PARENT"   VARCHAR2(20 BYTE),
  "V_ID_SUBTIPO_ULTIMO"   VARCHAR2(20 BYTE),
  "V_CODIGO_CPMS"         VARCHAR2(30 BYTE),
  "V_CODIGO_SEGUS"        VARCHAR2(30 BYTE),
  "V_ESTADO"              VARCHAR2(20 BYTE)   DEFAULT 'PENDIENTE',
  "T_CREATED_AT"          DATE                DEFAULT SYSDATE    NOT NULL,
  "V_CREATED_BY"          VARCHAR2(50 BYTE)   NOT NULL,
  "T_UPDATED_AT"          DATE,
  "V_UPDATED_BY"          VARCHAR2(50 BYTE),

  CONSTRAINT "PK_TBL_SOL_APOYO"     PRIMARY KEY ("I_ID"),
  CONSTRAINT "CK_SOLAP_PRIORIDAD"   CHECK ("V_PRIORIDAD" IN ('Normal','Urgente','Emergencia') OR "V_PRIORIDAD" IS NULL),
  CONSTRAINT "CK_SOLAP_ESTADO"      CHECK ("V_ESTADO"    IN ('PENDIENTE','ATENDIDO','CANCELADO')),
  CONSTRAINT "FK_SOLAP_ATENCION"    FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_SOLICITUD_APOYO" IS 'Tab 9 CE y Plan Control CC: Solicitudes de apoyo diagnóstico por jerarquía de sub-tipos de procedimiento CPMS.';

-- TBL_TRATAMIENTO
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_TRATAMIENTO" (
  "I_ID"                  NUMBER(19,0)         NOT NULL,
  "I_ATENCION_ID"         NUMBER(19,0)         NOT NULL,
  "V_CODIGO"              VARCHAR2(30 BYTE),
  "V_MEDICAMENTO"         VARCHAR2(200 BYTE)   NOT NULL,
  "V_DOSIS"               VARCHAR2(10 BYTE),
  "V_VIA"                 VARCHAR2(20 BYTE),
  "V_FRECUENCIA"          VARCHAR2(3 BYTE),
  "V_DURACION"            VARCHAR2(8 BYTE),
  "V_INDICACIONES"        VARCHAR2(500 BYTE),
  "V_INDICACIONES_NO_FARM" VARCHAR2(2000 BYTE),

  CONSTRAINT "PK_TBL_TRAT"        PRIMARY KEY ("I_ID"),
  CONSTRAINT "FK_TRAT_ATENCION"   FOREIGN KEY ("I_ATENCION_ID") REFERENCES "SCH_HCE_CONSULTA"."TBL_ATENCION" ("I_ID")
  -- CONSTRAINT "CK_TRAT_VIA"          CHECK (V_VIA IN ('Oral','EV','IM','Típico','Inhalado') OR V_VIA IS NULL)
);

COMMENT ON TABLE "SCH_HCE_CONSULTA"."TBL_TRATAMIENTO" IS 'Tab 8 CE: Tratamiento farmacológico indicado en la atención.';


-- TBL_EXAMEN_REGION
CREATE TABLE "SCH_HCE_CONSULTA"."TBL_EXAMEN_REGION" (
  "I_ID"                NUMBER(19,0)         NOT NULL,
  "I_EXAMEN_FISICO_ID"  NUMBER(19,0)         NOT NULL,
  "V_REGION"            VARCHAR2(60 BYTE)    NOT NULL,
  "V_HALLAZGOS"         VARCHAR2(1000 BYTE),

  CONSTRAINT "PK_TBL_EX_REG"         PRIMARY KEY ("I_ID"),
  CONSTRAINT "FK_EXREGION_EXFISICO"  FOREIGN KEY ("I_EXAMEN_FISICO_ID")
      REFERENCES "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO" ("I_ID")
);

COMMENT ON TABLE  "SCH_HCE_CONSULTA"."TBL_EXAMEN_REGION" IS 'Tab 5 CE: Hallazgos del examen físico por región corporal.';
COMMENT ON COLUMN "SCH_HCE_CONSULTA"."TBL_EXAMEN_REGION"."V_REGION" IS 'Aspecto General | Cabeza y Cuello | Tórax y Pulmones | Cardiovascular | Abdomen | Extremidades | Neurológico | Piel y Faneras.';


-- Indices

CREATE INDEX "SCH_HCE_CONSULTA"."IDX_DIAG_ATENCION"   ON "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO"    ("I_ATENCION_ID");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_DIAG_CIE10"      ON "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO"    ("V_CODIGO_CIE10");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_SOLAP_ATENCION"  ON "SCH_HCE_CONSULTA"."TBL_SOLICITUD_APOYO" ("I_ATENCION_ID");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_SOLAP_ESTADO"    ON "SCH_HCE_CONSULTA"."TBL_SOLICITUD_APOYO" ("V_ESTADO");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_TRAT_ATENCION"   ON "SCH_HCE_CONSULTA"."TBL_TRATAMIENTO"    ("I_ATENCION_ID");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_ATE_ADMISION"    ON "SCH_HCE_CONSULTA"."TBL_ATENCION"       ("I_ADMISION_ID");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_ATE_DNI"         ON "SCH_HCE_CONSULTA"."TBL_ATENCION"       ("V_DNI_PACIENTE");
CREATE INDEX "SCH_HCE_CONSULTA"."IDX_ATE_CE_PARENT"   ON "SCH_HCE_CONSULTA"."TBL_ATENCION"       ("I_CE_ATENCION_ID");


-- Triggers

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_ATENCION_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ATENCION"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ATENCION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_ANT_PERS_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ANT_PERSONAL"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ANT_PERSONAL.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_EX_FIS_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_EXAMEN_FISICO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_EXAMEN_FISICO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_ALERG_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ANT_ALERGICO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ANT_ALERGICO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_GINECO_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ANT_GINECO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ANT_GINECO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_ANT_QUIR_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ANT_QUIRURGICO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ANT_QUIRURGICO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_APP_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_APP"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_APP.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_HABITO_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_HABITO_RIESGO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_HABITO_RIESGO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_MED_CRON_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_MEDICACION_CRONICA"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_MEDICACION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_ANT_FAM_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_ANT_FAMILIAR"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ANT_FAMILIAR.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_DEC_CLIN_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_DECISION_CLINICA"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_DECISION_CLINICA.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_DEC_CTRL_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_DECISION_CONTROL"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_DECISION_CONTROL.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_DIAG_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_DIAGNOSTICO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_DIAGNOSTICO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_IND_NO_FARM_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_INDICACION_NO_FARM"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_INDICACION_NO_FARM.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_LISTPROB_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_LISTA_PROBLEMA"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_LISTA_PROBLEMA.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_MED_PLAN_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_MED_PLAN_CONTROL"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_MED_PLAN_CONTROL.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_MOTIVO_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_MOTIVO_CONSULTA"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_MOTIVO_CONSULTA.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_PLAN_CTRL_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_PLAN_CONTROL"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_PLAN_CONTROL.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_REV_SIST_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_REVISION_SISTEMA"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_REVISION_SISTEMA.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_SOAP_A_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_SOAP_ANALISIS"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_SOAP_ANALISIS.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_SOAP_O_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_SOAP_OBJETIVO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_SOAP_OBJETIVO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_SOAP_P_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_SOAP_PLAN"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_SOAP_PLAN.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_SOAP_S_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_SOAP_SUBJETIVO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_SOAP_SUBJETIVO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_SOL_APOYO_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_SOLICITUD_APOYO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_SOLICITUD_APOYO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_TRAT_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_TRATAMIENTO"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_TRATAMIENTO.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER "SCH_HCE_CONSULTA"."TRG_TBL_EX_REG_BI"
  BEFORE INSERT ON "SCH_HCE_CONSULTA"."TBL_EXAMEN_REGION"
  FOR EACH ROW
BEGIN
  IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_EXAMEN_REGION.NEXTVAL;
  END IF;
END;
/
