/*
  Esquema Filiacion - SCH_HCE_FILIACION.
  Script ordenado desde el DDL exportado.
*/

-- Secuencias
CREATE SEQUENCE SCH_HCE_FILIACION.SEQ_ADMISION START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SCH_HCE_FILIACION.SEQ_HISTORIA_CLINICA START WITH 2 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Tablas
CREATE TABLE SCH_HCE_FILIACION.TBL_ADMISION (
    I_ID NUMBER(19,0),
    I_HISTORIA_CLINICA_ID NUMBER(19,0),
    V_SITUACION VARCHAR2(30 BYTE),
    V_CONDICION VARCHAR2(30 BYTE),
    V_PARENTESCO VARCHAR2(50 BYTE),
    V_CARTA_GARANTIA_NRO VARCHAR2(30 BYTE),
    V_TIPO_SEGURO VARCHAR2(30 BYTE),
    V_PLAN_SALUD VARCHAR2(30 BYTE),
    V_TIPO_COBERTURA VARCHAR2(20 BYTE),
    V_TIPO_BENEFICIO VARCHAR2(60 BYTE),
    V_TIPO_ATENCION VARCHAR2(40 BYTE),
    V_ACTIVIDAD VARCHAR2(200 BYTE),
    V_SUB_ACTIVIDAD VARCHAR2(200 BYTE),
    V_CONSULTA_MEDICA VARCHAR2(100 BYTE),
    V_SERVICIO VARCHAR2(100 BYTE),
    T_FECHA_ATENCION DATE,
    V_CUI_IPRESS VARCHAR2(20 BYTE),
    V_IPRESS_RAZON_SOCIAL VARCHAR2(255 BYTE),
    V_IPRESS_SEDE VARCHAR2(255 BYTE),
    V_IPRESS_REGION VARCHAR2(100 BYTE),
    V_IPRESS_CATEGORIA VARCHAR2(20 BYTE),
    V_PROFESIONAL_NOMBRE VARCHAR2(70 BYTE),
    V_PROFESIONAL_PROFESION VARCHAR2(50 BYTE),
    V_PROFESIONAL_COLEGIATURA VARCHAR2(6 BYTE),
    V_ESTADO VARCHAR2(20 BYTE) DEFAULT 'ACTIVA',
    T_CREATED_AT DATE DEFAULT SYSDATE,
    V_CREATED_BY VARCHAR2(50 BYTE),
    T_UPDATED_AT DATE,
    V_UPDATED_BY VARCHAR2(50 BYTE)
);
COMMENT ON COLUMN SCH_HCE_FILIACION.TBL_ADMISION.V_TIPO_BENEFICIO IS 'Atención Ambulatoria | Maternidad | Preventivo Promocional | Oncológica | Rehabilitación | Salud Mental | Telesalud | Domiciliaria.';
COMMENT ON COLUMN SCH_HCE_FILIACION.TBL_ADMISION.V_CUI_IPRESS IS 'Código único de IPRESS (registro SUSALUD).';
COMMENT ON TABLE SCH_HCE_FILIACION.TBL_ADMISION IS 'Registro de admisión. Una historia clínica puede tener múltiples admisiones.';

CREATE TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA (
    I_ID NUMBER(19,0),
    V_NRO_HC VARCHAR2(20 BYTE),
    V_DNI_PACIENTE VARCHAR2(12 BYTE),
    V_APELLIDOS_PACIENTE VARCHAR2(255 BYTE),
    V_NOMBRES_PACIENTE VARCHAR2(255 BYTE),
    T_FECHA_NAC DATE,
    V_SEXO VARCHAR2(1 BYTE),
    V_ESTADO VARCHAR2(20 BYTE) DEFAULT 'ACTIVA',
    T_FECHA_APERTURA DATE DEFAULT SYSDATE,
    T_CREATED_AT DATE DEFAULT SYSDATE,
    V_CREATED_BY VARCHAR2(50 BYTE),
    T_UPDATED_AT DATE,
    V_UPDATED_BY VARCHAR2(50 BYTE)
);
COMMENT ON COLUMN SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA.V_NRO_HC IS 'Número legible de la HC. Ej: HC-0045231.';
COMMENT ON COLUMN SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA.V_DNI_PACIENTE IS 'DNI del asegurado. FK lógica al Padrón (servicio externo).';
COMMENT ON TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA  IS 'Cabecera de la Historia Clínica. Una por paciente/DNI.';

-- Datos de ejemplo
Insert into SCH_HCE_FILIACION.TBL_ADMISION (I_ID,I_HISTORIA_CLINICA_ID,V_SITUACION,V_CONDICION,V_PARENTESCO,V_CARTA_GARANTIA_NRO,V_TIPO_SEGURO,V_PLAN_SALUD,V_TIPO_COBERTURA,V_TIPO_BENEFICIO,V_TIPO_ATENCION,V_ACTIVIDAD,V_SUB_ACTIVIDAD,V_CONSULTA_MEDICA,V_SERVICIO,T_FECHA_ATENCION,V_CUI_IPRESS,V_IPRESS_RAZON_SOCIAL,V_IPRESS_SEDE,V_IPRESS_REGION,V_IPRESS_CATEGORIA,V_PROFESIONAL_NOMBRE,V_PROFESIONAL_PROFESION,V_PROFESIONAL_COLEGIATURA,V_ESTADO,T_CREATED_AT,V_CREATED_BY,T_UPDATED_AT,V_UPDATED_BY) values (1,1,'ACTIVO','DERECHOHABIENTE','DERECHOHABIENTE',null,'SALUDPOL','Específico','Regular','Atención Ambulatoria','Consulta Externa','Atención médica ambulatoria','Consulta médica',null,'Pediatría',to_date('19/05/26','DD/MM/RR'),'00037082','POLICLINICO MUNICIPAL CORAZON DE MARIA','MAGDALENA DEL MAR','LIMA','I-3','LUIS CARRANZA','Médico','12345','ACTIVA',to_date('19/05/26','DD/MM/RR'),'76262964',null,null);
Insert into SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA (I_ID,V_NRO_HC,V_DNI_PACIENTE,V_APELLIDOS_PACIENTE,V_NOMBRES_PACIENTE,T_FECHA_NAC,V_SEXO,V_ESTADO,T_FECHA_APERTURA,T_CREATED_AT,V_CREATED_BY,T_UPDATED_AT,V_UPDATED_BY) values (1,'05611249','05611249','LECCA GARCIA DE SANCHEZ','ENITT ELMIRA',to_date('02/07/66','DD/MM/RR'),'F','ACTIVA',to_date('19/05/26','DD/MM/RR'),to_date('19/05/26','DD/MM/RR'),'76262964',null,null);

-- Triggers de secuencias
CREATE OR REPLACE TRIGGER SCH_HCE_FILIACION.TRG_TBL_ADMISION_BI
    BEFORE INSERT ON SCH_HCE_FILIACION.TBL_ADMISION
    FOR EACH ROW
BEGIN
    IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_ADMISION.NEXTVAL;
    END IF;
END;

/

CREATE OR REPLACE TRIGGER SCH_HCE_FILIACION.TRG_TBL_HC_BI
    BEFORE INSERT ON SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA
    FOR EACH ROW
BEGIN
    IF :NEW.I_ID IS NULL THEN
    :NEW.I_ID := SEQ_HISTORIA_CLINICA.NEXTVAL;
    END IF;
END;

/

-- Constraints
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION MODIFY (I_ID NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION MODIFY (I_HISTORIA_CLINICA_ID NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION MODIFY (V_ESTADO NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION MODIFY (T_CREATED_AT NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION MODIFY (V_CREATED_BY NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION ADD CONSTRAINT CK_ADM_TIPO_COB CHECK (V_TIPO_COBERTURA IN ('Regular','Total') OR V_TIPO_COBERTURA IS NULL);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION ADD CONSTRAINT CK_ADM_TIPO_SEG CHECK (V_TIPO_SEGURO    IN ('SALUDPOL','EPS','SIS') OR V_TIPO_SEGURO IS NULL);
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION ADD CONSTRAINT PK_TBL_ADMISION PRIMARY KEY (I_ID)
    USING INDEX;
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (I_ID NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (V_NRO_HC NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (V_DNI_PACIENTE NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (V_ESTADO NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (T_FECHA_APERTURA NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (T_CREATED_AT NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA MODIFY (V_CREATED_BY NOT NULL ENABLE);
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA ADD CONSTRAINT CK_TBL_HC_SEXO CHECK (V_SEXO   IN ('M','F'));
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA ADD CONSTRAINT CK_TBL_HC_ESTADO CHECK (V_ESTADO IN ('ACTIVA','SUSPENDIDA','CERRADA'));
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA ADD CONSTRAINT PK_TBL_HC PRIMARY KEY (I_ID)
    USING INDEX;
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA ADD CONSTRAINT UQ_TBL_HC_NRO UNIQUE (V_NRO_HC)
    USING INDEX;
ALTER TABLE SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA ADD CONSTRAINT UQ_TBL_HC_DNI UNIQUE (V_DNI_PACIENTE)
    USING INDEX;

-- Relaciones
ALTER TABLE SCH_HCE_FILIACION.TBL_ADMISION ADD CONSTRAINT FK_TBL_ADM_HC FOREIGN KEY (I_HISTORIA_CLINICA_ID)
    REFERENCES SCH_HCE_FILIACION.TBL_HISTORIA_CLINICA (I_ID);
