spring.application.name=hce-filiacion
server.port=8092
server.servlet.context-path=/api/v1/hce

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREE
spring.datasource.username=SCH_HCE_FILIACION
spring.datasource.password=clave123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=SCH_HCLINICA
spring.jpa.open-in-view=false

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,http://localhost:5174,https://dev-hce.saludpol.gob.pe:26951

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.com.saludpol=INFO
logging.level.org.hibernate.SQL=OFF

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# services.gateway.url=http://localhost:8085
