spring.application.name=api-gateway
server.port=8085

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#Gateway Configuration
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

# Auth Service Route
spring.cloud.gateway.routes[0].id=service-auth
spring.cloud.gateway.routes[0].uri=https://dev-ios-be.saludpol.gob.pe:31289
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# User Route
spring.cloud.gateway.routes[1].id=service-users
# spring.cloud.gateway.routes[1].uri=lb://service-users
spring.cloud.gateway.routes[1].uri=https://dev-ios-be.saludpol.gob.pe:31289
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/users/**

# SMT Route
spring.cloud.gateway.routes[2].id=service-supervision-medica-tramas
spring.cloud.gateway.routes[2].uri=lb://service-supervision-medica-tramas
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/smt/**

# SPI Route
spring.cloud.gateway.routes[3].id=service-prestaciones-interoperabilidad
spring.cloud.gateway.routes[3].uri=lb://service-prestaciones-interoperabilidad
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/spi/**

# Maestros Route
spring.cloud.gateway.routes[4].id=service-maestros
spring.cloud.gateway.routes[4].uri=https://dev-ios-be.saludpol.gob.pe:31289
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/maestros/**

# Asegurados Route
spring.cloud.gateway.routes[5].id=service-asegurados
# spring.cloud.gateway.routes[5].uri=lb://service-asegurados
spring.cloud.gateway.routes[5].uri=https://dev-ios-be.saludpol.gob.pe:31289
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/asegurados/**

# Garantias Route
spring.cloud.gateway.routes[6].id=service-cartas-garantia-pasajes
spring.cloud.gateway.routes[6].uri=lb://service-cartas-garantia-pasajes
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/garantias/**

# Reembolso Route
spring.cloud.gateway.routes[7].id=service-reembolso
spring.cloud.gateway.routes[7].uri=lb://service-reembolso
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/reembolsos/**

# Mensajeria Route
spring.cloud.gateway.routes[8].id=service-mensajeria
spring.cloud.gateway.routes[8].uri=lb://service-mensajeria
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/mensajeria/**

# Reniec Route
spring.cloud.gateway.routes[9].id=service-reniec
spring.cloud.gateway.routes[9].uri=lb://service-reniec
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/reniec/**

# Tramite Reembolso Route
spring.cloud.gateway.routes[10].id=service-reembolso-tramite
spring.cloud.gateway.routes[10].uri=lb://service-reembolso-tramite
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/v1/reembolso-tramite/**

# Hospitalizacion Route
spring.cloud.gateway.routes[11].id=service-hospitalizacion
spring.cloud.gateway.routes[11].uri=lb://service-hospitalizacion
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/v1/hospitalizacion/**

# Reembolso Master Route
spring.cloud.gateway.routes[12].id=service-reembolso-master
spring.cloud.gateway.routes[12].uri=lb://service-reembolso-master
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/v1/reembolsos-master/**

# Carta Garantia Route
spring.cloud.gateway.routes[13].id=service-carta-garantia
spring.cloud.gateway.routes[13].uri=lb://service-carta-garantia
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/v1/carta-garantias/**

# Interaccion Proveedor Route
spring.cloud.gateway.routes[14].id=service-interaccion-proveedores
spring.cloud.gateway.routes[14].uri=lb://service-interaccion-proveedores
spring.cloud.gateway.routes[14].predicates[0]=Path=/api/v1/interaccion-proveedores/**

# Notificaciones Jobs Route
spring.cloud.gateway.routes[15].id=service-jobs-notificacion
spring.cloud.gateway.routes[15].uri=lb://service-jobs-notificacion
spring.cloud.gateway.routes[15].predicates[0]=Path=/api/v1/notificaciones/**

# Prestaciones Route
spring.cloud.gateway.routes[16].id=service-prestaciones
spring.cloud.gateway.routes[16].uri=lb://service-prestaciones
spring.cloud.gateway.routes[16].predicates[0]=Path=/api/v1/prestaciones/**

# APS con Solicitud Route
spring.cloud.gateway.routes[17].id=service-aps
spring.cloud.gateway.routes[17].uri=lb://service-aps
spring.cloud.gateway.routes[17].predicates[0]=Path=/api/v1/autorizaciones-convenio/**

# APS Directa Route
# Aps Solicitud
spring.cloud.gateway.routes[18].id=service-aps-solicitud
spring.cloud.gateway.routes[18].uri=lb://service-aps-solicitud
spring.cloud.gateway.routes[18].predicates[0]=Path=/api/v1/aps-solicitud/**

#SGPS
# Solicitud Referencia
spring.cloud.gateway.routes[19].id=service-sgps
spring.cloud.gateway.routes[19].uri=lb://service-sgps
spring.cloud.gateway.routes[19].predicates[0]=Path=/api/v1/sgps/**

# OAO Route
spring.cloud.gateway.routes[20].id=service-oap
spring.cloud.gateway.routes[20].uri=lb://service-oap
spring.cloud.gateway.routes[20].predicates[0]=Path=/api/v1/oap/**

# HCE - Filiacion (Admision e Historia Clinica)
spring.cloud.gateway.routes[21].id=hce-filiacion
spring.cloud.gateway.routes[21].uri=lb://hce-filiacion
spring.cloud.gateway.routes[21].predicates[0]=Path=/api/v1/hce/admision/**

# HCE - Consulta Externa y Control y Seguimiento
spring.cloud.gateway.routes[22].id=hce-consulta-externa
spring.cloud.gateway.routes[22].uri=lb://hce-consulta-externa
spring.cloud.gateway.routes[22].predicates[0]=Path=/api/v1/hce/consulta/**

# HCE - Emergencia
spring.cloud.gateway.routes[23].id=hce-emergencia
spring.cloud.gateway.routes[23].uri=lb://hce-emergencia
spring.cloud.gateway.routes[23].predicates[0]=Path=/api/v1/hce/emergencia/**

